[versions]
adam = "0.5.10"
clikt = "5.1.0"
mordant = "3.0.2"
slf4j = "2.0.17"
shadow = "9.4.1"
buildconfig = "6.0.9"
mcp = "0.12.0"
kotlinx-io = "0.9.0"
ktor = "3.4.3"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }

[libraries]
adam = { module = "com.malinskiy.adam:adam", version.ref = "adam" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
mordant = { module = "com.github.ajalt.mordant:mordant", version.ref = "mordant" }
slf4j = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
mcp-kotlin = { module = "io.modelcontextprotocol:kotlin-sdk", version.ref = "mcp" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
